### ISSUE TITLE
Contact form removes edit button functionality when I enable and publish a test form. 

### ISSUE THREAD

**Issue by tenzingjake** [jordanlev/c5_custom_contact_form#10]

**Comment by jordanlev** [comment]
What version of C5 are you using? Does your form markup use any javascript? Can you paste your form markup here so I can see it?

**Comment by tenzingjake** [comment]
Hi Jordan,

This happens when I dont use my form and use one of your examples. I am
using 5.6.1.2



On Tue, Nov 10, 2015 at 10:20 AM, Jordan Lev <notifications@github.com>
wrote:

> What version of C5 are you using? Does your form markup use any
> javascript? Can you paste your form markup here so I can see it?
>
>
>
> > On Nov 10, 2015, at 8:51 AM, tenzingjake <notifications@github.com>
> wrote:
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jordanlev/c5_custom_contact_form/issues/10#issuecomment-155449512>
> .
>



-- 
*Jake Bhatt *
Web Developer
Tenzing  |  416-367-1557  |  519-642-4404

**Comment by tenzingjake** [comment]
I haven't created a form yet.

On Tue, Nov 10, 2015 at 10:37 AM, Jake Bhatt <jake@gotenzing.com> wrote:

> Hi Jordan,
>
> This happens when I dont use my form and use one of your examples. I am
> using 5.6.1.2
>
>
>
> On Tue, Nov 10, 2015 at 10:20 AM, Jordan Lev <notifications@github.com>
> wrote:
>
>> What version of C5 are you using? Does your form markup use any
>> javascript? Can you paste your form markup here so I can see it?
>>
>>
>>
>> > On Nov 10, 2015, at 8:51 AM, tenzingjake <notifications@github.com>
>> wrote:
>> >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jordanlev/c5_custom_contact_form/issues/10#issuecomment-155449512>
>> .
>>
>
>
>
> --
> *Jake Bhatt *
> Web Developer
> Tenzing  |  416-367-1557  |  519-642-4404
>



-- 
*Jake Bhatt *
Web Developer
Tenzing  |  416-367-1557  |  519-642-4404

**Comment by tenzingjake** [comment]
its for this site - canadascreditunions.com , but I am working in a local
environment. Also how do you get your add on to work with radio buttons?

I have this code, but only displays one button -

<?php echo $form->label('agriculture', 'Agriculture'); ?>
<?php echo $form->radio('low', 'medium', 'high'); ?>

On Tue, Nov 10, 2015 at 10:20 AM, Jordan Lev <notifications@github.com>
wrote:

> What version of C5 are you using? Does your form markup use any
> javascript? Can you paste your form markup here so I can see it?
>
>
>
> > On Nov 10, 2015, at 8:51 AM, tenzingjake <notifications@github.com>
> wrote:
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jordanlev/c5_custom_contact_form/issues/10#issuecomment-155449512>
> .
>



-- 
*Jake Bhatt *
Web Developer
Tenzing  |  416-367-1557  |  519-642-4404

**Comment by tenzingjake** [comment]
Nevermind the radio buttons  I got that figured out, still got that other
issue that removes the edit button. Any ideas or where to look?

On Tue, Nov 10, 2015 at 10:20 AM, Jordan Lev <notifications@github.com>
wrote:

> What version of C5 are you using? Does your form markup use any
> javascript? Can you paste your form markup here so I can see it?
>
>
>
> > On Nov 10, 2015, at 8:51 AM, tenzingjake <notifications@github.com>
> wrote:
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jordanlev/c5_custom_contact_form/issues/10#issuecomment-155449512>
> .
>



-- 
*Jake Bhatt *
Web Developer
Tenzing  |  416-367-1557  |  519-642-4404

**Comment by tenzingjake** [comment]
Hi Jordan,

No worries on those issues, I created a custom form and it seems to have
fixed itself.

Cheers,

On Tue, Nov 10, 2015 at 12:19 PM, Jake Bhatt <jake@gotenzing.com> wrote:

> Nevermind the radio buttons  I got that figured out, still got that other
> issue that removes the edit button. Any ideas or where to look?
>
> On Tue, Nov 10, 2015 at 10:20 AM, Jordan Lev <notifications@github.com>
> wrote:
>
>> What version of C5 are you using? Does your form markup use any
>> javascript? Can you paste your form markup here so I can see it?
>>
>>
>>
>> > On Nov 10, 2015, at 8:51 AM, tenzingjake <notifications@github.com>
>> wrote:
>> >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jordanlev/c5_custom_contact_form/issues/10#issuecomment-155449512>
>> .
>>
>
>
>
> --
> *Jake Bhatt *
> Web Developer
> Tenzing  |  416-367-1557  |  519-642-4404
>



-- 
*Jake Bhatt *
Web Developer
Tenzing  |  416-367-1557  |  519-642-4404
