### ISSUE TITLE
Broken package (handle custom_contact_form).

### ISSUE THREAD

**Issue by arvi** [jordanlev/c5_custom_contact_form#7]
Hello :)

I'm currently stuck in Step 2, which is:

Install the addon via Dashboard > Extend Concrete5 > Install.

It says "Broken package (handle custom_contact_form)."

Can't Install
This package is corrupted. Make sure it has a valid controller.php and that it has been updated for 5.7 or later. I'm using Concrete5 5.7.4.2.

Any suggestions how to solve this. I need to create a modal with a form submit and would like to see if this package would help me achieve that.

Thanks a lot!

**Comment by jordanlev** [comment]
I haven't updated this for 5.7, so it only works with Concrete 5.6. And unfortunately I don't know when I'll be able to update it for 5.7.
